stages:
  - build
  - deploy

build de la partie front:
  image: node:18
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploiement de la partie client:
  image:
    name: pockost/phploy:4.9.3
    entrypoint:  [""]
  stage: deploy
  script:
    - phploy -s front-prod